/* The supported compiler and target matrix, checked against the corpus that
   defines it.

   ARCHITECTURE.md and METHODS.md both state the ASM2C_GNU_V1 provenance
   matrix: GCC and Clang, PIC and non-PIC, O0 through O3. The corpus is what
   that sentence is about, and the corpus is regenerated outside this
   repository. So the sentence can quietly stop being true - a new compiler or
   a new optimization level appears in the dataset and nothing here notices
   that the profile no longer covers what it claims to.

   This reads the dataset manifest and compares it against what the profile
   actually declares. Two directions matter and they fail differently:

     - the corpus grew a compiler or a codegen mode the profile does not
       cover, which means proofs are being asked for inputs outside the frozen
       provenance;
     - the profile declares an axis the corpus does not exercise, which is not
       a defect but is worth stating, because an unexercised axis is an
       untested claim.

   Optimization level is deliberately not a contract axis. ARCHITECTURE.md
   calls it validation provenance rather than a semantic switch, so the check
   is that the manifest's levels stay inside the documented range, not that
   some field encodes them. */

#include "quodlibet/semantics.h"

#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <gtest/gtest.h>

namespace {

namespace fs = std::filesystem;

/* Where the asm2c dataset manifest lives. It is outside this repository and
   is regenerated by the corpus builder, so the path is overridable and its
   absence is stated rather than treated as a pass. */
constexpr char kSummaryEnvironment[] = "QL_ASM2C_SUMMARY";
/* The same location spelled the two ways this repository is reached: from
   Windows, and from a WSL build of the same working tree. Without the second
   spelling the check would skip on every Linux run for no better reason than
   a drive letter, which is exactly the silence it exists to prevent. */
const char *const kSummaryDefaults[] = {
    "D:/projects/machine-model/datasets/records-local/summary.json",
    "/mnt/d/projects/machine-model/datasets/records-local/summary.json",
};

std::string first_existing_default() {
    for (const char *candidate : kSummaryDefaults) {
        if (fs::exists(candidate)) {
            return std::string(candidate);
        }
    }
    return std::string(kSummaryDefaults[0]);
}

std::string summary_path() {
#if defined(_WIN32)
    char *value = nullptr;
    std::size_t size = 0u;
    std::string result;
    if (_dupenv_s(&value, &size, kSummaryEnvironment) == 0 &&
        value != nullptr && value[0] != '\0') {
        result.assign(value);
    }
    std::free(value);
    return result.empty() ? first_existing_default() : result;
#else
    const char *value = std::getenv(kSummaryEnvironment);
    return (value == nullptr || value[0] == '\0') ? first_existing_default()
                                                  : std::string(value);
#endif
}

/* A deliberately small reader for one flat array of strings under a top-level
   key. Pulling in a JSON library here would mean the test depended on the
   same parser the core does, and this only has to read two fixed keys out of
   a machine-generated file.

   It reports failure rather than guessing: anything that is not `"key" : [`
   followed by quoted strings and a `]` yields an empty result, and the caller
   treats that as a failed read rather than as an empty array. */
bool read_string_array(const std::string &json, const std::string &key,
                       std::vector<std::string> *output) {
    const std::string needle = "\"" + key + "\"";
    std::size_t at = json.find(needle);

    output->clear();
    if (at == std::string::npos) {
        return false;
    }
    at = json.find(':', at + needle.size());
    if (at == std::string::npos) {
        return false;
    }
    ++at;
    while (at < json.size() && std::isspace(static_cast<unsigned char>(
                                   json[at])) != 0) {
        ++at;
    }
    if (at >= json.size() || json[at] != '[') {
        return false;
    }
    ++at;
    for (;;) {
        while (at < json.size() &&
               (std::isspace(static_cast<unsigned char>(json[at])) != 0 ||
                json[at] == ',')) {
            ++at;
        }
        if (at >= json.size()) {
            return false;
        }
        if (json[at] == ']') {
            return true;
        }
        if (json[at] != '"') {
            return false;
        }
        const std::size_t start = ++at;
        while (at < json.size() && json[at] != '"') {
            /* The manifest holds plain identifiers. An escape would mean the
               file is richer than this reader admits, and guessing past it
               would be worse than saying so. */
            if (json[at] == '\\') {
                return false;
            }
            ++at;
        }
        if (at >= json.size()) {
            return false;
        }
        output->push_back(json.substr(start, at - start));
        ++at;
    }
}

/* What the profile declares it covers. ql_semantic_contract_init fills the
   frozen ASM2C_GNU_V1 provenance, so this reads the declaration rather than
   restating it: a change to the profile shows up here instead of being
   duplicated. */
struct Matrix {
    std::uint32_t compiler_families;
    std::uint32_t codegen_modes;
};

Matrix profile_matrix() {
    ql_semantic_contract_v1 contract{};
    ql_semantic_contract_init(&contract);
    return Matrix{contract.compiler_families, contract.codegen_modes};
}

/* How a corpus compiler name maps onto the two provenance axes. The corpus
   names a toolchain and a codegen mode in one string; the profile keeps them
   apart. */
struct CompilerMapping {
    const char *corpus_name;
    ql_compiler_family family;
    ql_codegen_mode codegen;
};

const CompilerMapping kKnownCompilers[] = {
    {"clang", QL_COMPILER_FAMILY_CLANG, QL_CODEGEN_PIC},
    {"clang-nopic", QL_COMPILER_FAMILY_CLANG, QL_CODEGEN_NON_PIC},
    {"gcc", QL_COMPILER_FAMILY_GCC, QL_CODEGEN_PIC},
    {"gcc-nopic", QL_COMPILER_FAMILY_GCC, QL_CODEGEN_NON_PIC},
};

const CompilerMapping *find_mapping(const std::string &name) {
    for (const CompilerMapping &mapping : kKnownCompilers) {
        if (name == mapping.corpus_name) {
            return &mapping;
        }
    }
    return nullptr;
}

/* The optimization names ARCHITECTURE.md and METHODS.md both commit to. */
bool is_documented_optimization(const std::string &name) {
    return name == "O0" || name == "O1" || name == "O2" || name == "O3";
}

class TargetMatrix : public ::testing::Test {
protected:
    void SetUp() override {
        const std::string path = summary_path();
        if (!fs::exists(path)) {
            /* The dataset is not part of this repository and a machine
               without it cannot answer the question. What it must not do is
               answer "yes" by default. */
            GTEST_SKIP()
                << "the asm2c dataset manifest is not at " << path
                << "; set " << kSummaryEnvironment << " to point at it. "
                << "This check cannot run without the corpus it is about.";
        }
        std::ifstream input(path, std::ios::binary);
        ASSERT_TRUE(input.is_open()) << "could not open " << path;
        std::ostringstream buffer;
        buffer << input.rdbuf();
        json_ = buffer.str();
        ASSERT_FALSE(json_.empty()) << path << " is empty";
        path_ = path;
    }

    std::string json_;
    std::string path_;
};

/* The reader is checked on inputs whose answers are known before it is
   trusted with the real manifest. A hand-rolled scanner that silently
   returned an empty list would turn every check below into a pass. */
TEST(TargetMatrixReader, ReadsAnArrayAndRefusesWhatItCannotRead) {
    std::vector<std::string> values;

    EXPECT_TRUE(read_string_array(R"({"compilers": ["a", "b"]})", "compilers",
                                  &values));
    EXPECT_EQ(std::vector<std::string>({"a", "b"}), values);

    EXPECT_TRUE(read_string_array(R"({"compilers":[]})", "compilers",
                                  &values));
    EXPECT_TRUE(values.empty());

    EXPECT_TRUE(read_string_array(
        "{\"x\":1,\n \"compilers\" : [ \"clang\" ,\n \"clang-nopic\" ]\n}",
        "compilers", &values));
    EXPECT_EQ(std::vector<std::string>({"clang", "clang-nopic"}), values);

    /* Absent key, wrong shape, unterminated, and an escape this reader does
       not admit: each is a failed read, never an empty answer. */
    EXPECT_FALSE(read_string_array(R"({"other":["a"]})", "compilers",
                                   &values));
    EXPECT_FALSE(read_string_array(R"({"compilers":"a"})", "compilers",
                                   &values));
    EXPECT_FALSE(read_string_array(R"({"compilers":["a")", "compilers",
                                   &values));
    EXPECT_FALSE(read_string_array(R"({"compilers":[1,2]})", "compilers",
                                   &values));
    EXPECT_FALSE(read_string_array(R"({"compilers":["a\tb"]})", "compilers",
                                   &values));
}

/* Every compiler the corpus contains must fall inside the provenance the
   profile declares. This is the direction that matters: a corpus that grew a
   toolchain the profile does not cover means judgements are being asked for
   inputs outside the frozen matrix. */
TEST_F(TargetMatrix, EveryCorpusCompilerIsInsideTheDeclaredProvenance) {
    std::vector<std::string> compilers;
    ASSERT_TRUE(read_string_array(json_, "compilers", &compilers))
        << "could not read the compilers array from " << path_;
    ASSERT_FALSE(compilers.empty())
        << path_ << " lists no compilers, so it cannot be compared";

    const Matrix matrix = profile_matrix();
    for (const std::string &name : compilers) {
        SCOPED_TRACE(::testing::Message() << "corpus compiler " << name);
        const CompilerMapping *mapping = find_mapping(name);
        ASSERT_NE(nullptr, mapping)
            << "the corpus uses a compiler this check does not know how to "
               "place on the profile's axes. Either the profile covers it and "
               "the mapping table here needs the entry, or it does not and "
               "ASM2C_GNU_V1 no longer covers the corpus.";
        EXPECT_NE(0u, matrix.compiler_families &
                          static_cast<std::uint32_t>(mapping->family))
            << "the profile does not declare this compiler family";
        EXPECT_NE(0u, matrix.codegen_modes &
                          static_cast<std::uint32_t>(mapping->codegen))
            << "the profile does not declare this codegen mode";
    }
}

/* Optimization level is validation provenance rather than a semantic switch,
   so what is checked is that the corpus stays inside the documented range.
   A level outside it would mean the documents describe a corpus that no
   longer exists. */
TEST_F(TargetMatrix, EveryCorpusOptimizationLevelIsDocumented) {
    std::vector<std::string> optimizations;
    ASSERT_TRUE(read_string_array(json_, "optimizations", &optimizations))
        << "could not read the optimizations array from " << path_;
    ASSERT_FALSE(optimizations.empty())
        << path_ << " lists no optimization levels";

    for (const std::string &name : optimizations) {
        EXPECT_TRUE(is_documented_optimization(name))
            << "the corpus uses optimization level '" << name
            << "', which ARCHITECTURE.md and METHODS.md do not list. Both "
               "documents commit to O0 through O3.";
    }
}

/* The other direction. An axis the profile declares but the corpus never
   exercises is not a defect - the profile is deliberately wider than any one
   corpus - but it is an untested claim, and the run should say so rather than
   leave it to be discovered later. */
TEST_F(TargetMatrix, ReportsProfileAxesTheCorpusDoesNotExercise) {
    std::vector<std::string> compilers;
    ASSERT_TRUE(read_string_array(json_, "compilers", &compilers));

    std::uint32_t exercised_families = 0u;
    std::uint32_t exercised_codegen = 0u;
    for (const std::string &name : compilers) {
        const CompilerMapping *mapping = find_mapping(name);
        if (mapping != nullptr) {
            exercised_families |= static_cast<std::uint32_t>(mapping->family);
            exercised_codegen |= static_cast<std::uint32_t>(mapping->codegen);
        }
    }

    const Matrix matrix = profile_matrix();
    const std::uint32_t unexercised_families =
        matrix.compiler_families & ~exercised_families;
    const std::uint32_t unexercised_codegen =
        matrix.codegen_modes & ~exercised_codegen;

    if ((unexercised_families & QL_COMPILER_FAMILY_GCC) != 0u) {
        std::cout << "[  NOTE    ] the profile declares GCC and this corpus "
                     "contains none"
                  << std::endl;
    }
    if ((unexercised_families & QL_COMPILER_FAMILY_CLANG) != 0u) {
        std::cout << "[  NOTE    ] the profile declares Clang and this corpus "
                     "contains none"
                  << std::endl;
    }
    if (unexercised_codegen != 0u) {
        std::cout << "[  NOTE    ] the profile declares a codegen mode this "
                     "corpus does not exercise"
                  << std::endl;
    }
    /* Both axes must be exercised by something, or the matrix is a claim with
       nothing behind it at all. */
    EXPECT_NE(0u, exercised_families);
    EXPECT_NE(0u, exercised_codegen);
}

/* The profile's own declaration has to stay internally consistent: whatever
   ql_semantic_contract_init fills must validate, and must be exactly the
   frozen ASM2C_GNU_V1 target. If this drifts, the two tests above would be
   comparing the corpus against something other than the documented profile. */
TEST(TargetMatrixProfile, TheDeclaredProfileIsTheFrozenAsm2cTarget) {
    ql_semantic_contract_v1 contract{};
    ql_error error{};

    ql_semantic_contract_init(&contract);
    EXPECT_EQ(QL_STATUS_OK,
              ql_semantic_contract_validate(&contract, &error))
        << error.message;
    EXPECT_EQ(QL_C_DIALECT_ASM2C_GNU_V1, contract.c_dialect);
    EXPECT_EQ(QL_TARGET_ABI_X86_64_LINUX_SYSV_LP64, contract.target_abi);
    /* ARCHITECTURE.md: "GCC and Clang, PIC and non-PIC". */
    EXPECT_EQ(static_cast<std::uint32_t>(QL_COMPILER_FAMILY_GCC |
                                         QL_COMPILER_FAMILY_CLANG),
              contract.compiler_families);
    EXPECT_EQ(static_cast<std::uint32_t>(QL_CODEGEN_PIC |
                                         QL_CODEGEN_NON_PIC),
              contract.codegen_modes);
    /* Optimization level is validation provenance, so no contract field
       encodes it. Nothing to assert but the absence, which the struct's own
       shape already enforces. */
}

}  // namespace
